package docs:adder@0.1.0;

interface simple {
    add-int: func(x: u32, y: u32) -> u32;
    add-str: func(x: f32, y: f32) -> f32;
    add-double: func(x: f64, y: f64) -> f64;
    concat: func(x: string, y: string) -> string;
    reverse: func(x: string) -> string;
}

world adder {
    export simple;
}