// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
#include "adder.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `docs:adder/simple@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#concat")))
void __wasm_export_exports_docs_adder_simple_concat_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#reverse")))
void __wasm_export_exports_docs_adder_simple_reverse_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void adder_list_u8_free(adder_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void adder_option_list_u8_free(adder_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    adder_list_u8_free(&ptr->val);
  }
}

void exports_docs_adder_simple_customer_free(exports_docs_adder_simple_customer_t *ptr) {
  adder_string_free(&ptr->name);
  adder_option_list_u8_free(&ptr->activity);
}

void adder_string_set(adder_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void adder_string_dup(adder_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void adder_string_free(adder_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-int")))
int32_t __wasm_export_exports_docs_adder_simple_add_int(int32_t arg, int32_t arg0) {
  uint32_t ret = exports_docs_adder_simple_add_int((uint32_t) (arg), (uint32_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-str")))
float __wasm_export_exports_docs_adder_simple_add_str(float arg, float arg0) {
  float ret = exports_docs_adder_simple_add_str(arg, arg0);
  return ret;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-double")))
double __wasm_export_exports_docs_adder_simple_add_double(double arg, double arg0) {
  double ret = exports_docs_adder_simple_add_double(arg, arg0);
  return ret;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#concat")))
uint8_t * __wasm_export_exports_docs_adder_simple_concat(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  adder_string_t arg3 = (adder_string_t) { (uint8_t*)(arg), (arg0) };
  adder_string_t arg4 = (adder_string_t) { (uint8_t*)(arg1), (arg2) };
  adder_string_t ret;
  exports_docs_adder_simple_concat(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#reverse")))
uint8_t * __wasm_export_exports_docs_adder_simple_reverse(uint8_t * arg, size_t arg0) {
  adder_string_t arg1 = (adder_string_t) { (uint8_t*)(arg), (arg0) };
  adder_string_t ret;
  exports_docs_adder_simple_reverse(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_adder(void);
void __component_type_object_force_link_adder_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_adder();
}
