// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
#include "adder.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `docs:adder/simple@0.1.0`




__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#concat")))
void __wasm_export_exports_docs_adder_simple_concat_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#reverse")))
void __wasm_export_exports_docs_adder_simple_reverse_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}



__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#scale-points")))
void __wasm_export_exports_docs_adder_simple_scale_points_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 16;
      (void) base;
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#get-statistics-int")))
void __wasm_export_exports_docs_adder_simple_get_statistics_int_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 4;
      (void) base;
    }
    free(ptr);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_docs:adder/simple@0.1.0#get-statistics-list-int")))
void __wasm_export_exports_docs_adder_simple_get_statistics_list_int_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 4;
      (void) base;
    }
    free(ptr);
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(8)))
static uint8_t RET_AREA[16];

// Helper Functions

void exports_docs_adder_simple_list_point_free(exports_docs_adder_simple_list_point_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_docs_adder_simple_point_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void adder_list_u32_free(adder_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void adder_list_f32_free(adder_list_f32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    float *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void adder_list_list_u32_free(adder_list_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    adder_list_u32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      adder_list_u32_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void adder_string_set(adder_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void adder_string_dup(adder_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void adder_string_free(adder_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-int")))
int32_t __wasm_export_exports_docs_adder_simple_add_int(int32_t arg, int32_t arg0) {
  uint32_t ret = exports_docs_adder_simple_add_int((uint32_t) (arg), (uint32_t) (arg0));
  return (int32_t) (ret);
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-float")))
float __wasm_export_exports_docs_adder_simple_add_float(float arg, float arg0) {
  float ret = exports_docs_adder_simple_add_float(arg, arg0);
  return ret;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-double")))
double __wasm_export_exports_docs_adder_simple_add_double(double arg, double arg0) {
  double ret = exports_docs_adder_simple_add_double(arg, arg0);
  return ret;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#concat")))
uint8_t * __wasm_export_exports_docs_adder_simple_concat(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2) {
  adder_string_t arg3 = (adder_string_t) { (uint8_t*)(arg), (arg0) };
  adder_string_t arg4 = (adder_string_t) { (uint8_t*)(arg1), (arg2) };
  adder_string_t ret;
  exports_docs_adder_simple_concat(&arg3, &arg4, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#reverse")))
uint8_t * __wasm_export_exports_docs_adder_simple_reverse(uint8_t * arg, size_t arg0) {
  adder_string_t arg1 = (adder_string_t) { (uint8_t*)(arg), (arg0) };
  adder_string_t ret;
  exports_docs_adder_simple_reverse(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#add-point")))
uint8_t * __wasm_export_exports_docs_adder_simple_add_point(int32_t arg, int32_t arg0, double arg1, int32_t arg2, int32_t arg3, double arg4) {
  exports_docs_adder_simple_point_t arg5 = (exports_docs_adder_simple_point_t) {
    (uint32_t) (uint32_t) (arg),
    (uint32_t) (uint32_t) (arg0),
    (double) arg1,
  };
  exports_docs_adder_simple_point_t arg6 = (exports_docs_adder_simple_point_t) {
    (uint32_t) (uint32_t) (arg2),
    (uint32_t) (uint32_t) (arg3),
    (double) arg4,
  };
  exports_docs_adder_simple_point_t ret;
  exports_docs_adder_simple_add_point(&arg5, &arg6, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((int32_t*)(ptr + 0)) = (int32_t) ((ret).x);
  *((int32_t*)(ptr + 4)) = (int32_t) ((ret).y);
  *((double*)(ptr + 8)) = (ret).z;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#sub-point")))
uint8_t * __wasm_export_exports_docs_adder_simple_sub_point(int32_t arg, int32_t arg0, double arg1, int32_t arg2, int32_t arg3, double arg4) {
  exports_docs_adder_simple_point_t arg5 = (exports_docs_adder_simple_point_t) {
    (uint32_t) (uint32_t) (arg),
    (uint32_t) (uint32_t) (arg0),
    (double) arg1,
  };
  exports_docs_adder_simple_point_t arg6 = (exports_docs_adder_simple_point_t) {
    (uint32_t) (uint32_t) (arg2),
    (uint32_t) (uint32_t) (arg3),
    (double) arg4,
  };
  exports_docs_adder_simple_point_t ret;
  exports_docs_adder_simple_sub_point(&arg5, &arg6, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((int32_t*)(ptr + 0)) = (int32_t) ((ret).x);
  *((int32_t*)(ptr + 4)) = (int32_t) ((ret).y);
  *((double*)(ptr + 8)) = (ret).z;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#scale-points")))
uint8_t * __wasm_export_exports_docs_adder_simple_scale_points(uint8_t * arg, size_t arg0, int32_t arg1) {
  exports_docs_adder_simple_list_point_t arg2 = (exports_docs_adder_simple_list_point_t) { (exports_docs_adder_simple_point_t*)(arg), (arg0) };
  exports_docs_adder_simple_list_point_t ret;
  exports_docs_adder_simple_scale_points(&arg2, (uint32_t) (arg1), &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#get-statistics-int")))
uint8_t * __wasm_export_exports_docs_adder_simple_get_statistics_int(uint8_t * arg, size_t arg0) {
  adder_list_u32_t arg1 = (adder_list_u32_t) { (uint32_t*)(arg), (arg0) };
  adder_list_f32_t ret;
  exports_docs_adder_simple_get_statistics_int(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("docs:adder/simple@0.1.0#get-statistics-list-int")))
uint8_t * __wasm_export_exports_docs_adder_simple_get_statistics_list_int(uint8_t * arg, size_t arg0) {
  adder_list_list_u32_t arg1 = (adder_list_list_u32_t) { (adder_list_u32_t*)(arg), (arg0) };
  adder_list_f32_t ret;
  exports_docs_adder_simple_get_statistics_list_int(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_adder(void);
void __component_type_object_force_link_adder_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_adder();
}
